### ISSUE TITLE
dpkg-buildpackage fails

### ISSUE THREAD

**Issue by stefangweichinger** [rbrito/usbmount#10]
README: "sudo dpkg-buildpackage -us -uc -b"
it fails. You depend on "lockfile-progs", right? ;-)

**Comment by mathieulj** [comment]
I'm not sure if your asking for help with something specific but your issue is lacking information. As written in the readme works for debian stretch. If you wish to add more information (ex. debian version, what doesn't work,...) it may help understand the issue, otherwise my recommendation would be to close it as un-reproducible.

The following is tested on a blank system via docker:
```bash
$ sudo docker run -it debian:stretch /bin/bash
# apt update && apt install -y git debhelper
# cd /opt
# git clone https://github.com/rbrito/usbmount.git
# cd usbmount
# dpkg-buildpackage -us -uc -b
# file ../usbmount_0.0.24_all.deb
```

**Comment by stefangweichinger** [comment]
debian stretch on hardware, not docker:

~/usbmount# dpkg-buildpackage -us -uc -b
dpkg-buildpackage: Information: Quellpaket usbmount
dpkg-buildpackage: Information: Quellversion 0.0.24
dpkg-buildpackage: Information: Quelldistribution unstable
dpkg-buildpackage: Information: Quelle geändert durch Mathieu Letendre-Jauniaux <mathieulj@gmail.com>
dpkg-buildpackage: Information: Host-Architektur amd64
 dpkg-source --before-build usbmount
dpkg-checkbuilddeps: Fehler: Nicht erfüllte Bauabhängigkeiten: build-essential:native
dpkg-buildpackage: Warnung: Bauabhängigkeiten/-konflikte nicht erfüllt; Abbruch
dpkg-buildpackage: Warnung: (Verwenden Sie -d, um sich darüber hinwegzusetzen.)

**Comment by mathieulj** [comment]
You seem to be missing the `build-essential` package which is a general dependency for building most software.

**Comment by mathieulj** [comment]
I assume you installed with `dpkg -i ...` if your dependencies were not installed. If so, you can follow up with `apt-get -f install` to install missing dependencies. A simpler alternative for local installs is to use a tool like `gdebi` that will install the dependencies automatically even when installing from a local package.
