### ISSUE TITLE
copying to USB stick fails on raspbian stretch, permission denied

### ISSUE THREAD

**Issue by OliverGruenberg** [rbrito/usbmount#23]
Hi there,
on a new installation of Raspbian usbmount does not work.
Also installed the newest version of usbmount via

sudo apt-get install debhelper
git clone https://github.com/rbrito/usbmount.git
cd usbmount
sudo dpkg-buildpackage -us -uc -b
cd ..
sudo apt install  ./usbmount_0.0.24_all.deb
sudo reboot

Got a "cp: cannot create regular file '/media/usb/test.txt': Permission denied".

I edited /lib/systemd/system/systemd-udevd.service and changed MountFlags=shared, no success after reboot.

Any help?

**Comment by mathieulj** [comment]
Without more information, the most likely cause for your permission denied error is that your device is mounted read-only to the user you are logged in as. Have you tried with sudo?

Have a look at the [/etc/usbmount/usbmount.conf](https://github.com/rbrito/usbmount/blob/master/usbmount.conf) file. You can set your mount options there with the `MOUNTOPTIONS` variable.

**Comment by OliverGruenberg** [comment]
I've compared with an older installation (which worked)...

Problem found: On the new system FS_MOUNTOPTIONS was not set, changed it to

FS_MOUNTOPTIONS="-fstype=vfat,gid=users,dmask=0007,fmask=0117"

and it works perfectly now!
