### ISSUE TITLE
usbmount was removed from latest Debian Stretch

### ISSUE THREAD

**Issue by mafrosis** [rbrito/usbmount#5]
Automated report:
https://tracker.debian.org/news/834311

Seems this is the specific bug that caused it:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=774149

https://tracker.debian.org/pkg/usbmount

**Comment by rbrito** [comment]
Hi, @mafrosis,

Do you want to adopt this package? Please see: https://github.com/rbrito/usbmount/pull/3#issuecomment-341261178

Thanks,

Rogério.

**Comment by mafrosis** [comment]
Hi @rbrito, I'm sorry I don't have time to take on this project

**Comment by rbrito** [comment]
@mafrosis, fair enough.

**Comment by mathieulj** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=774149 Was resolved by #6

**Comment by rbrito** [comment]
I guess that we can close this issue now, therefore.
